# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.12

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key: "$CI_PIPELINE_ID"
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

build-job:
  stage: build
  script:
    - pip install .

run-pytest:
  stage: test
  script:
    - export PYTHONPATH=$(pwd)
    - pip install -r requirements.txt
    - pip install bs4
    - pip install pytest pytest-cov
    - pytest --cov=. --cov-config=.coveragerc
    - coverage report
    - coverage xml -o reports/coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

run-ruff:
  stage: test
  script:
    - pip install ruff
    - ruff check ./src

# Dependabot is scheduled to run weekly, will not be run on every CI invoke (see rules at bottom of this section)
# Starting with '.' means not run by GitLab CI/CD. Our package ecosystems will extend this (currently pip).
.dependabot:
  image:
    name: docker.io/andrcuns/dependabot-gitlab:0.36.0
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
    PACKAGE_MANAGER: $CI_JOB_NAME
    RAILS_ENV: production
    SETTINGS__GITLAB_URL: $CI_SERVER_URL
    SETTINGS__STANDALONE: "true"
  before_script:
    - cd /home/dependabot/app
  script:
    - bundle exec rake "dependabot:update[$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME,$PACKAGE_MANAGER,/]"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "dependabot"'
pip:
  extends: .dependabot
