build-job:
  stage: build
  script:
    - apt-get install -y python-dev python-pip
    - pip install -e .

run-pytest:
  stage: test
  script:
    pytest

run-flake:
  stage: test
  script:
    flake8