#
# This sample config file is to be used as a guide to create/populate config.yml in the same location
# Whenever altering this file, remember to update config_handler.py::_validate_config()
#
Logging:
  # log_dir: string location to store logs
  # log_level: Minimum level to show in log - DEBUG, WARNING, INFO, ERROR, CRITICAL
  # log_tag: user defined tag to prepend to log file name.  Can be empty string or used for convenience - "PROD_, DEV_, USERNAME_, etc."
  log_dir: "/grp/roman/RFP/DEV/scratch/"
  log_level: INFO
  log_tag: "DEV_"
