crds_files:
  crds_ready_dir: "/grp/roman/RFP_REFERENCE_FILES/TVAC1"

submission_form:
  deliverer: "User updated information."
  other_email: "User updated information."
  file_type: "User updated information."
  history_updated: true
  pedigree_updated: true
  keywords_checked: true
  descrip_updated: true
  useafter_updated: true
  useafter_matches: "User updated information."
  compliance_verified: "User updated information."
  etc_delivery: false
  calpipe_version: "User updated information."
  replacement_files: true
  old_reference_files: "User updated information."
  replacing_badfiles: "User updated information."
  jira_issue: "User updated information."
  table_rows_changed: "User updated information."
  reprocess_affected: false
  modes_affected: "User updated information."
  change_level: "MODERATE"
  correctness_testing: "None"
  additional_considerations: "None"
  description: "User updated information."
