#
# These example values are to be used as a template to guide the user in creating CONFIG.YML
# CONFIG.YML should not exist in our repo
# Whenever altering this file template, remember to update config_handler.py::_validate_config() and your local config.yml
#
Logging:
  # log_dir: string location to store logs
  # log_level: Minimum level to show in log - DEBUG, WARNING, INFO, ERROR, CRITICAL
  # log_tag: user defined tag to prepend to log file name.  Can be empty string or used for convenience - "PROD_, DEV_, USERNAME_, etc."
  log_dir: "/PATH/TO/LOG/DIR"
  log_level: INFO
  log_tag: "DEV_"

DataFiles:
  # ingest_dir: string location to ingest uncalibrated files
  # prep_dir: string location to store prepped files
  # crds_ready_dir: string location to store CRDS ready deliverable reference files
  ingest_dir: "/PATH/TO/DATAFILES/INGEST"
  prep_dir: "/PATH/TO/DATAFILES/PREPPED"
  crds_ready_dir: "/PATH/TO/DATAFILES/CRDS_READY"