#
# This configuration file determines which quality control checks are executed after a reference file object
# with a complete and valid data model tree is populated.
#

dark_quality_controls:
  check_mean_dark_rate_flag: "True",
  check_med_dark_rate_flag: "True",
  check_std_dark_rate_flag: "True",
  check_num_hot_pix_flag: "True",
  check_num_dead_pix_flag: "True",
  check_num_unreliable_pix_flag: "True",
  check_num_warm_pix_flag: "True"

  # These are the values from this page but supplied here
  # https://innerspace.stsci.edu/display/RI/RFP+Database+Tables
  # We should have this config file be version controlled but question now is
  # do have separate files for each ref_type to version control this reference values separately
  # or keep all reference values in one file? What do you think is better?
  max_mean_dark_rate_reference_value: 0.01,
  max_med_dark_rate_reference_value: 0.01,
  max_std_dark_rate_reference_value: 0.01,
  max_num_hot_pix_reference_value: 1e6,
  max_num_dead_pix_reference_value: 1e6,
  max_num_unreliable_pix_reference_value: 1e6,
  max_num_warm_pix_reference_value: 1e6

readnoise_quality_controls:
  check_mean_readnoise_flag: "True",
  check_med_readnoise_flag: "True",
  check_std_readnoise_flag: "True",

  # These are the values from this page but supplied here
  max_mean_dark_rate_reference_value: 5.0,
  max_med_dark_rate_reference_value: 5.0,
  max_std_dark_rate_reference_value: 5.0
